# SPDX-License-Identifier: Apache-2.0
"""Gate-level functional check of the generated netlists with iverilog and the sky130 models.

    python3 tb/run_iverilog.py [U N D DA] [--random 2000] [--seed 1]

Per variant: stimulus = the exhaustive set (U: 32 inputs; masked: all 32768 (x, mask, r))
followed by --random uniform rows; build/<V>/dut.v is simulated with tb/tb_dut.v and the
PDK's functional cell models (-DFUNCTIONAL -DUNIT_DELAY=#1), once without and once with
-DUSE_POWER_PINS. The dumped output ports of every window are compared
  (1) bit for bit with the Python cycle-accurate model of graph.json, and
  (2) after XOR-ing the shares, with the S-box of the row captured L windows earlier.
The first L windows (flip-flops still X) are skipped. Prints PASS/FAIL per run; exit code 1
on any failure. Needs iverilog/vvp on PATH and the PDK (env PDK or ~/.ciel/sky130A).
Scratch files go to build/<V>/iverilog/.
"""
import argparse
import json
import os
import subprocess
import sys
import time

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "model"))
sys.path.insert(0, os.path.join(ROOT, "gen"))

import pdk                                   # noqa: E402
from ascon_sbox import SBOX_NP               # noqa: E402
from netgraph import Graph                   # noqa: E402
from stimulus import make_stimulus           # noqa: E402


def write_wrapper(path, ports):
    ins, outs = ports["inputs"], ports["outputs"]
    conns = ["        .CLK(CLK)"]
    conns += ["        .%s(din[%d])" % (p["name"], k) for k, p in enumerate(ins)]
    conns += ["        .%s(dout[%d])" % (p["name"], k) for k, p in enumerate(outs)]
    L = ["// SPDX-License-Identifier: Apache-2.0",
         "// Generated by tb/run_iverilog.py: vector-port wrapper around %s." % ports["subckt"],
         "`default_nettype none",
         "module dut_vec (input wire CLK, input wire [%d:0] din, output wire [%d:0] dout);"
         % (len(ins) - 1, len(outs) - 1),
         "`ifdef USE_POWER_PINS", "    supply1 vpwr;", "    supply0 vgnd;", "`endif",
         "    %s u (" % ports["subckt"], ",\n".join(conns),
         "`ifdef USE_POWER_PINS", "        , .VPWR(vpwr), .VGND(vgnd)", "`endif", "    );",
         "endmodule", "`default_nettype wire", ""]
    with open(path, "w") as f:
        f.write("\n".join(L))


def run_variant(v, n_random, seed, power_pins):
    d = os.path.join(ROOT, "build", v)
    with open(os.path.join(d, "ports.json")) as f:
        ports = json.load(f)
    g = Graph(d)
    L = g.latency
    ex, mex = make_stimulus(ports, "exhaustive")
    rn, mrn = make_stimulus(ports, "random", n_random, seed)
    pad, _ = make_stimulus(ports, "random", L, seed + 1)
    stim = np.concatenate([ex, rn, pad])
    x = np.concatenate([mex["x"], mrn["x"]])
    n = len(stim)

    work = os.path.join(d, "iverilog")
    os.makedirs(work, exist_ok=True)
    tag = "pp" if power_pins else "np"
    vec, out, vvp = (os.path.join(work, "%s.%s" % (s, tag)) for s in ("vec", "out", "vvp"))
    with open(vec, "w") as f:
        f.write("\n".join("".join(str(b) for b in row[::-1]) for row in stim) + "\n")
    write_wrapper(os.path.join(work, "dut_vec.v"), ports)
    P = pdk.paths()
    cmd = ["iverilog", "-g2005", "-DFUNCTIONAL", "-DUNIT_DELAY=#1", "-o", vvp,
           "-Ptb.N_IN=%d" % len(ports["inputs"]), "-Ptb.N_OUT=%d" % len(ports["outputs"]), "-Ptb.N_CYC=%d" % n]
    if power_pins:
        cmd.append("-DUSE_POWER_PINS")
    cmd += [os.path.join(ROOT, "tb", "tb_dut.v"), os.path.join(work, "dut_vec.v"), os.path.join(d, "dut.v"),
            P["verilog_primitives"], P["verilog_cells"]]
    t0 = time.time()
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        return False
    r = subprocess.run(["vvp", "-n", vvp, "+vec=" + vec, "+out=" + out], capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout + r.stderr)
        return False
    with open(out) as f:
        lines = f.read().split()
    dt = time.time() - t0
    if len(lines) != n:
        print("%s: expected %d output lines, got %d" % (v, n, len(lines)))
        return False
    got = np.array([[int(ch) if ch in "01" else 2 for ch in s[::-1]] for s in lines[L:]], dtype=np.uint8)
    want = g.output_values(g.simulate(stim))[L:]
    mism_model = int((got != want).any(1).sum())
    n_rows = len(x)
    y = g.recombine(got[:n_rows] & 1)
    bad_x = int((got[:n_rows] > 1).any(1).sum())
    mism_sbox = int((y != SBOX_NP[x]).sum()) + bad_x
    ok = mism_model == 0 and mism_sbox == 0
    print("%-2s %-15s %6d windows (%d exhaustive + %d random): vs graph model %d mismatches, "
          "vs S-box %d mismatches  [%.1f s]  %s"
          % (v, "USE_POWER_PINS" if power_pins else "no power pins", n - L, len(ex), n_random,
             mism_model, mism_sbox, dt, "PASS" if ok else "FAIL"))
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("variants", nargs="*", default=["U", "N", "D", "DA"])
    ap.add_argument("--random", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=1)
    a = ap.parse_args()
    ok = True
    for v in a.variants:
        for pp in (False, True):
            ok &= run_variant(v, a.random, a.seed, pp)
    print("ALL PASS" if ok else "FAILURES")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
